// Generated by CIRCT firtool-1.75.0
// Generated by CIRCT firtool-1.75.0
module ApproxMac (
    input  logic signed [ 7:0] din,
    win,
    input  logic signed [19:0] accin,
    output logic signed [19:0] out
);
  wire signed [15:0] prod;
  wire signed [19:0] prod_norm;
  u2s mul (
      .A(din),
      .B(win),
      .O(prod)
  );
  assign prod_norm = {{4{prod[15]}}, prod};
  assign out = prod_norm + accin;


endmodule
