// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module FrontendTLB(	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
  input         reset,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
  input         io_clients_0_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  input  [39:0] io_clients_0_req_bits_tlb_req_vaddr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  output        io_clients_0_resp_miss,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  output [31:0] io_clients_0_resp_paddr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  input         io_clients_1_req_valid,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  input  [39:0] io_clients_1_req_bits_tlb_req_vaddr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  output        io_clients_1_resp_miss,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  output [31:0] io_clients_1_resp_paddr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  input         io_exp_0_flush_retry,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  input         io_exp_0_flush_skip,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  input         io_exp_1_flush_retry,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
  input         io_exp_1_flush_skip	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:152:14]
);

  wire [31:0] _tlbs_1_io_resp_paddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:159:39]
  wire [31:0] _tlbs_0_io_resp_paddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:159:39]
  reg         last_translated_valid;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:178:40]
  reg  [38:0] last_translated_vpn;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:179:38]
  reg  [31:0] last_translated_ppn;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:180:38]
  reg         tlbs_0_io_req_valid_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:190:27]
  reg  [39:0] tlbs_0_io_req_bits_REG_tlb_req_vaddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:191:22]
  reg  [31:0] io_clients_0_resp_paddr_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:207:35]
  reg         io_clients_0_resp_miss_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:208:35]
  reg         last_translated_valid_1;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:178:40]
  reg  [38:0] last_translated_vpn_1;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:179:38]
  reg  [31:0] last_translated_ppn_1;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:180:38]
  reg         tlbs_1_io_req_valid_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:190:27]
  reg  [39:0] tlbs_1_io_req_bits_REG_tlb_req_vaddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:191:22]
  reg  [31:0] io_clients_1_resp_paddr_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:207:35]
  reg         io_clients_1_resp_miss_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:208:35]
  wire        l0_tlb_hit = last_translated_valid & io_clients_0_req_bits_tlb_req_vaddr[39:12] == {1'h0, last_translated_vpn[38:12]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:178:40, :179:38, :182:{44,79,100,125}]
  wire        l0_tlb_hit_1 = last_translated_valid_1 & io_clients_1_req_bits_tlb_req_vaddr[39:12] == {1'h0, last_translated_vpn_1[38:12]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:178:40, :179:38, :182:{44,79,100,125}]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
    if (reset) begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
      last_translated_valid <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:178:40]
      last_translated_vpn <= 39'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:179:38]
      last_translated_ppn <= 32'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:180:38]
      last_translated_valid_1 <= 1'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:178:40]
      last_translated_vpn_1 <= 39'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:179:38]
      last_translated_ppn_1 <= 32'h0;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:180:38]
    end
    else begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
      last_translated_valid <= ~(io_exp_0_flush_retry | io_exp_0_flush_skip) & (tlbs_0_io_req_valid_REG | last_translated_valid);	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:25:49, :178:40, :190:27, :193:44, :194:29, :199:31, :200:29]
      if (tlbs_0_io_req_valid_REG) begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:190:27]
        last_translated_vpn <= tlbs_0_io_req_bits_REG_tlb_req_vaddr[38:0];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:179:38, :191:22, :195:27]
        last_translated_ppn <= _tlbs_0_io_resp_paddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:159:39, :180:38]
      end
      last_translated_valid_1 <= ~(io_exp_1_flush_retry | io_exp_1_flush_skip) & (tlbs_1_io_req_valid_REG | last_translated_valid_1);	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:25:49, :178:40, :190:27, :193:44, :194:29, :199:31, :200:29]
      if (tlbs_1_io_req_valid_REG) begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:190:27]
        last_translated_vpn_1 <= tlbs_1_io_req_bits_REG_tlb_req_vaddr[38:0];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:179:38, :191:22, :195:27]
        last_translated_ppn_1 <= _tlbs_1_io_resp_paddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:159:39, :180:38]
      end
    end
    tlbs_0_io_req_valid_REG <= io_clients_0_req_valid & ~l0_tlb_hit;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:182:44, :190:{27,45,48}]
    tlbs_0_io_req_bits_REG_tlb_req_vaddr <= io_clients_0_req_bits_tlb_req_vaddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:191:22]
    io_clients_0_resp_paddr_REG <= {last_translated_ppn[31:12], io_clients_0_req_bits_tlb_req_vaddr[11:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:180:38, :183:{27,48,91}, :207:35]
    io_clients_0_resp_miss_REG <= l0_tlb_hit;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:182:44, :208:35]
    tlbs_1_io_req_valid_REG <= io_clients_1_req_valid & ~l0_tlb_hit_1;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:182:44, :190:{27,45,48}]
    tlbs_1_io_req_bits_REG_tlb_req_vaddr <= io_clients_1_req_bits_tlb_req_vaddr;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:191:22]
    io_clients_1_resp_paddr_REG <= {last_translated_ppn_1[31:12], io_clients_1_req_bits_tlb_req_vaddr[11:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:180:38, :183:{27,48,91}, :207:35]
    io_clients_1_resp_miss_REG <= l0_tlb_hit_1;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:182:44, :208:35]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:16];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
        for (logic [4:0] i = 5'h0; i < 5'h11; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
        end	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
        last_translated_valid = _RANDOM[5'h0][0];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :178:40]
        last_translated_vpn = {_RANDOM[5'h0][31:1], _RANDOM[5'h1][7:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :178:40, :179:38]
        last_translated_ppn = {_RANDOM[5'h1][31:8], _RANDOM[5'h2][7:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :179:38, :180:38]
        tlbs_0_io_req_valid_REG = _RANDOM[5'h2][8];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :180:38, :190:27]
        tlbs_0_io_req_bits_REG_tlb_req_vaddr = {_RANDOM[5'h2][31:9], _RANDOM[5'h3][16:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :180:38, :191:22]
        io_clients_0_resp_paddr_REG = {_RANDOM[5'h7][31:5], _RANDOM[5'h8][4:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :207:35]
        io_clients_0_resp_miss_REG = _RANDOM[5'h8][5];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :207:35, :208:35]
        last_translated_valid_1 = _RANDOM[5'h8][6];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :178:40, :207:35]
        last_translated_vpn_1 = {_RANDOM[5'h8][31:7], _RANDOM[5'h9][13:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :179:38, :207:35]
        last_translated_ppn_1 = {_RANDOM[5'h9][31:14], _RANDOM[5'hA][13:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :179:38, :180:38]
        tlbs_1_io_req_valid_REG = _RANDOM[5'hA][14];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :180:38, :190:27]
        tlbs_1_io_req_bits_REG_tlb_req_vaddr = {_RANDOM[5'hA][31:15], _RANDOM[5'hB][22:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :180:38, :191:22]
        io_clients_1_resp_paddr_REG = {_RANDOM[5'hF][31:11], _RANDOM[5'h10][10:0]};	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :207:35]
        io_clients_1_resp_miss_REG = _RANDOM[5'h10][11];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :207:35, :208:35]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  UselessDecoupledTLB tlbs_0 (	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:159:39]
    .io_req_bits_tlb_req_vaddr (tlbs_0_io_req_bits_REG_tlb_req_vaddr),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:191:22]
    .io_resp_paddr             (_tlbs_0_io_resp_paddr)
  );	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:159:39]
  UselessDecoupledTLB tlbs_1 (	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:159:39]
    .io_req_bits_tlb_req_vaddr (tlbs_1_io_req_bits_REG_tlb_req_vaddr),	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:191:22]
    .io_resp_paddr             (_tlbs_1_io_resp_paddr)
  );	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:159:39]
  assign io_clients_0_resp_miss = ~tlbs_0_io_req_valid_REG & ~io_clients_0_resp_miss_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :190:27, :203:23, :204:19, :208:{24,27,35}]
  assign io_clients_0_resp_paddr = tlbs_0_io_req_valid_REG ? _tlbs_0_io_resp_paddr : io_clients_0_resp_paddr_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :159:39, :190:27, :203:23, :204:19, :207:{25,35}]
  assign io_clients_1_resp_miss = ~tlbs_1_io_req_valid_REG & ~io_clients_1_resp_miss_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :190:27, :203:23, :204:19, :208:{24,27,35}]
  assign io_clients_1_resp_paddr = tlbs_1_io_req_valid_REG ? _tlbs_1_io_resp_paddr : io_clients_1_resp_paddr_REG;	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:146:7, :159:39, :190:27, :203:23, :204:19, :207:{25,35}]
endmodule

