// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module PE_256(	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
  input         clock,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
  input  [7:0]  io_in_a,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input  [19:0] io_in_b,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input  [19:0] io_in_d,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output [7:0]  io_out_a,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output [19:0] io_out_b,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output [19:0] io_out_c,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input         io_in_control_dataflow,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input         io_in_control_propagate,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output        io_out_control_dataflow,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output        io_out_control_propagate,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input  [2:0]  io_in_id,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output [2:0]  io_out_id,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input         io_in_last,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output        io_out_last,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  input         io_in_valid,	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
  output        io_out_valid	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:35:14]
);

  reg [7:0] c1;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:70:15]
  reg [7:0] c2;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:71:15]
  always @(posedge clock) begin	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
    if (io_in_valid & io_in_control_propagate)	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:102:95, :141:17, :142:8]
      c1 <= io_in_d[7:0];	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:70:15, :124:10]
    if (~(~io_in_valid | io_in_control_propagate))	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:71:15, :102:95, :119:30, :130:10, :141:{9,17}, :143:8]
      c2 <= io_in_d[7:0];	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:71:15, :124:10]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
    initial begin	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
        `INIT_RANDOM_PROLOG_	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
        c1 = _RANDOM[/*Zero width*/ 1'b0][7:0];	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7, :70:15]
        c2 = _RANDOM[/*Zero width*/ 1'b0][15:8];	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7, :70:15, :71:15]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MacUnit mac_unit (	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:64:24]
    .io_in_a  (io_in_a),
    .io_in_b  (io_in_control_propagate ? c2 : c1),	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:70:15, :71:15, :119:30, :121:24, :127:24]
    .io_in_c  (io_in_b),
    .io_out_d (io_out_b)
  );	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:64:24]
  assign io_out_a = io_in_a;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
  assign io_out_c = io_in_control_propagate ? {{12{c1[7]}}, c1} : {{12{c2[7]}}, c2};	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7, :70:15, :71:15, :119:30, :120:16, :126:16]
  assign io_out_control_dataflow = io_in_control_dataflow;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
  assign io_out_control_propagate = io_in_control_propagate;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
  assign io_out_id = io_in_id;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
  assign io_out_last = io_in_last;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
  assign io_out_valid = io_in_valid;	// @[generators/gemmini/src/main/scala/gemmini/PE.scala:31:7]
endmodule

