// Generated by CIRCT firtool-1.75.0
module UselessDecoupledTLB(	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:28:7]
  input  [39:0] io_req_bits_tlb_req_vaddr,	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:32:14]
  output [31:0] io_resp_paddr	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:32:14]
);

  assign io_resp_paddr = io_req_bits_tlb_req_vaddr[31:0];	// @[generators/gemmini/src/main/scala/gemmini/FrontendTLB.scala:28:7, :74:19]
endmodule

