./common/src/gemmini_top.sv
./common/src/rocc_adapter.sv
./common/src/gemmini_wrap.sv
./common/src/rocc_fifo.sv
./common/src/utils/axi_demux_simple.sv
./common/src/utils/axi_atop_filter.sv
./common/src/utils/axi_lite_regs.sv
./common/src/utils/stream_register.sv
./common/src/utils/spill_register_flushable.sv
./common/src/utils/axi_intf.sv
./common/src/utils/counter.sv
./common/src/utils/addr_decode_dync.sv
./common/src/utils/cf_math_pkg.sv
./common/src/utils/id_queue.sv
./common/src/utils/rr_arb_tree.sv
./common/src/utils/spill_register.sv
./common/src/utils/axi_multicut.sv
./common/src/utils/axi_burst_splitter_gran.sv
./common/src/utils/axi_burst_splitter.sv
./common/src/utils/axi_cut.sv
./common/src/utils/axi_pkg.sv
./common/src/utils/axi_to_axi_lite.sv
./common/src/utils/lzc.sv
./common/src/utils/axi_err_slv.sv
./common/src/utils/delta_counter.sv
./common/src/utils/axi_lite_to_axi.sv
./common/src/utils/fifo_v3.sv
./common/src/utils/onehot_to_bin.sv
./common/src/utils/addr_decode.sv
./common/src/utils/axi_id_setter.sv
./common/src/tl2axi_pkg.sv
./common/src/tl2axi.sv
./gemmini/AccPipe.sv
./gemmini/Arbiter3_TLBundleAWithInfo.sv
./gemmini/Mesh.sv
./gemmini/TwoPortSyncMem.sv
./gemmini/mul8_RippleCarryArrayMultiplier_wrapper.v
./gemmini/Pipeline_4.sv
./gemmini/Queue6_TagWithIdAndTotalRows.sv
./gemmini/ScalePipe.sv
./gemmini/ram_2x625.sv
./gemmini/Queue4_ScratchpadReadResp.sv
./gemmini/ReservationStation.sv
./gemmini/Arbiter3_UInt6.sv
./gemmini/RecFNToIN_e8_s24_i8.sv
./gemmini/Queue8_GemminiCmd.sv
./gemmini/Queue2_TLBundleD_a32d128s4k4z4u.sv
./gemmini/MultiHeadedQueue_1.sv
./gemmini/plusarg_reader.sv
./gemmini/PixelRepeater_1.sv
./gemmini/LoopMatmul.sv
./gemmini/ram_2x257.sv
./gemmini/ram_2x383.sv
./gemmini/RRArbiter.sv
./gemmini/TagQueue.sv
./gemmini/Arbiter2_ScratchpadReadReq.sv
./gemmini/LoopMatmulStC.sv
./gemmini/LoopConvLdInput.sv
./gemmini/MulAddRecFNToRaw_preMul_e8_s24.sv
./gemmini/ram_6x8.sv
./gemmini/RoundRawFNToRecFN_e8_s24.sv
./gemmini/MulAddRecFN_e8_s24.sv
./gemmini/DMACommandTracker_1.sv
./gemmini/ram_2x191.sv
./gemmini/ram_5x190.sv
./gemmini/mul8_RippleCarryArrayMultiplier.v
./gemmini/Pipeline_3.sv
./gemmini/TLBuffer_a32d128s5k4z4u.sv
./gemmini/ram_6x383.sv
./gemmini/LoopMatmulExecute.sv
./gemmini/ram_4x129.sv
./gemmini/StreamReaderCore.sv
./gemmini/mem.sv
./gemmini/Queue5_ScratchpadMemWriteRequest.sv
./gemmini/Arbiter5_RoCCCommand.sv
./gemmini/LoopMatmulLdD.sv
./gemmini/INToRecFN_i8_e8_s24.sv
./gemmini/ram_5x83.sv
./gemmini/Pipeline.sv
./gemmini/Pipeline_2.sv
./gemmini/BeatMerger.sv
./gemmini/Im2Col.sv
./gemmini/ZeroWriter.sv
./gemmini/LoopMatmulLdA.sv
./gemmini/LoopConvExecute.sv
./gemmini/RoundAnyRawFNToRecFN_ie4_is8_oe8_os24.sv
./gemmini/ram_2x274.sv
./gemmini/ram_8x246.sv
./gemmini/FrontendTLB.sv
./gemmini/ram_2x192.sv
./gemmini/LoopMatmulStCSpad.sv
./gemmini/Queue2_TLBundleD_a32d128s5k4z4u.sv
./gemmini/RoundAnyRawFNToRecFN_ie8_is26_oe8_os24.sv
./gemmini/Pipeline_1.sv
./gemmini/StreamWriter.sv
./gemmini/RoundAnyRawFNToRecFN_ie6_is32_oe8_os24.sv
./gemmini/LoopConvLdBias.sv
./gemmini/Queue1_AccumulatorReadResp.sv
./gemmini/Pipeline_6.sv
./gemmini/CounterController.sv
./gemmini/Queue2_TLBundleA_a32d128s5k4z4u.sv
./gemmini/ram_2x148.sv
./gemmini/PE.sv
./gemmini/MulAddRecFNToRaw_postMul_e8_s24.sv
./gemmini/StreamReader.sv
./gemmini/AlwaysOutTransposer.sv
./gemmini/Queue1_TLBundleAWithInfo_2.sv
./gemmini/Queue2_VectorScalarMultiplierReq.sv
./gemmini/Queue2_GemminiCmd.sv
./gemmini/VectorScalarMultiplier.sv
./gemmini/mems.sv
./gemmini/INToRecFN_i32_e8_s24.sv
./gemmini/DMACommandTracker.sv
./gemmini/Queue5_ComputeCntlSignals.sv
./gemmini/Queue1_TLBundleAWithInfo_3.sv
./gemmini/MacUnit.sv
./gemmini/VectorScalarMultiplier_1.sv
./gemmini/TLXbar_i2_o1_a32d128s5k4z4u.sv
./gemmini/LoopConv.sv
./gemmini/StoreController.sv
./gemmini/RecFNToIN_e8_s24_i32.sv
./gemmini/PE_256.sv
./gemmini/WeightedArbiter.sv
./gemmini/Queue1_ScratchpadReadResp.sv
./gemmini/Scratchpad.sv
./gemmini/AccumulatorMem.sv
./gemmini/Queue6_ScratchpadMemWriteRequest.sv
./gemmini/XactTracker.sv
./gemmini/ram_5x258.sv
./gemmini/Queue2_VectorScalarMultiplierReq_1.sv
./gemmini/Queue2_TLBundleA_a32d128s4k4z4u.sv
./gemmini/Queue5_ScratchpadMemReadRequest.sv
./gemmini/AccumulatorScale.sv
./gemmini/Arbiter2_TLBundleAWithInfo.sv
./gemmini/Queue2_NormalizedInput.sv
./gemmini/LoadController.sv
./gemmini/Queue1_TLBundleAWithInfo.sv
./gemmini/LoopMatmulLdB.sv
./gemmini/LoopConvSt.sv
./gemmini/PixelRepeater.sv
./gemmini/Tile.sv
./gemmini/TransposePreloadUnroller.sv
./gemmini/TLBuffer_a32d128s4k4z4u.sv
./gemmini/ExecuteController.sv
./gemmini/ram_2x139.sv
./gemmini/LoopConvLdWeight.sv
./gemmini/Pipeline_5.sv
./gemmini/Queue5_im2colRowSignals.sv
./gemmini/ram_2x550.sv
./gemmini/CounterFile.sv
./gemmini/mem_0.sv
./gemmini/UselessDecoupledTLB.sv
./gemmini/Queue2_ScratchpadMemWriteRequest.sv
./gemmini/Gemmini.sv
./gemmini/MultiHeadedQueue.sv
./gemmini/AccPipeShared.sv
./gemmini/ScratchpadBank.sv
./gemmini/approximate_arithmetic.sv
./gemmini/MeshWithDelays.sv
./common/include/tl2axi.svh
./common/src/utils/assertions.svh
./common/src/utils/port.svh
./common/src/utils/assign.svh
./common/src/utils/typedef.svh
./common/src/utils/registers.svh
